// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ai-learn-english/internal/database/model"
)

func newAlembicVersion(db *gorm.DB, opts ...gen.DOOption) alembicVersion {
	_alembicVersion := alembicVersion{}

	_alembicVersion.alembicVersionDo.UseDB(db, opts...)
	_alembicVersion.alembicVersionDo.UseModel(&model.AlembicVersion{})

	tableName := _alembicVersion.alembicVersionDo.TableName()
	_alembicVersion.ALL = field.NewAsterisk(tableName)
	_alembicVersion.VersionNum = field.NewString(tableName, "version_num")

	_alembicVersion.fillFieldMap()

	return _alembicVersion
}

type alembicVersion struct {
	alembicVersionDo alembicVersionDo

	ALL        field.Asterisk
	VersionNum field.String

	fieldMap map[string]field.Expr
}

func (a alembicVersion) Table(newTableName string) *alembicVersion {
	a.alembicVersionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alembicVersion) As(alias string) *alembicVersion {
	a.alembicVersionDo.DO = *(a.alembicVersionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alembicVersion) updateTableName(table string) *alembicVersion {
	a.ALL = field.NewAsterisk(table)
	a.VersionNum = field.NewString(table, "version_num")

	a.fillFieldMap()

	return a
}

func (a *alembicVersion) WithContext(ctx context.Context) IAlembicVersionDo {
	return a.alembicVersionDo.WithContext(ctx)
}

func (a alembicVersion) TableName() string { return a.alembicVersionDo.TableName() }

func (a alembicVersion) Alias() string { return a.alembicVersionDo.Alias() }

func (a alembicVersion) Columns(cols ...field.Expr) gen.Columns {
	return a.alembicVersionDo.Columns(cols...)
}

func (a *alembicVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alembicVersion) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 1)
	a.fieldMap["version_num"] = a.VersionNum
}

func (a alembicVersion) clone(db *gorm.DB) alembicVersion {
	a.alembicVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alembicVersion) replaceDB(db *gorm.DB) alembicVersion {
	a.alembicVersionDo.ReplaceDB(db)
	return a
}

type alembicVersionDo struct{ gen.DO }

type IAlembicVersionDo interface {
	gen.SubQuery
	Debug() IAlembicVersionDo
	WithContext(ctx context.Context) IAlembicVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlembicVersionDo
	WriteDB() IAlembicVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlembicVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlembicVersionDo
	Not(conds ...gen.Condition) IAlembicVersionDo
	Or(conds ...gen.Condition) IAlembicVersionDo
	Select(conds ...field.Expr) IAlembicVersionDo
	Where(conds ...gen.Condition) IAlembicVersionDo
	Order(conds ...field.Expr) IAlembicVersionDo
	Distinct(cols ...field.Expr) IAlembicVersionDo
	Omit(cols ...field.Expr) IAlembicVersionDo
	Join(table schema.Tabler, on ...field.Expr) IAlembicVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlembicVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlembicVersionDo
	Group(cols ...field.Expr) IAlembicVersionDo
	Having(conds ...gen.Condition) IAlembicVersionDo
	Limit(limit int) IAlembicVersionDo
	Offset(offset int) IAlembicVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlembicVersionDo
	Unscoped() IAlembicVersionDo
	Create(values ...*model.AlembicVersion) error
	CreateInBatches(values []*model.AlembicVersion, batchSize int) error
	Save(values ...*model.AlembicVersion) error
	First() (*model.AlembicVersion, error)
	Take() (*model.AlembicVersion, error)
	Last() (*model.AlembicVersion, error)
	Find() ([]*model.AlembicVersion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlembicVersion, err error)
	FindInBatches(result *[]*model.AlembicVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlembicVersion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlembicVersionDo
	Assign(attrs ...field.AssignExpr) IAlembicVersionDo
	Joins(fields ...field.RelationField) IAlembicVersionDo
	Preload(fields ...field.RelationField) IAlembicVersionDo
	FirstOrInit() (*model.AlembicVersion, error)
	FirstOrCreate() (*model.AlembicVersion, error)
	FindByPage(offset int, limit int) (result []*model.AlembicVersion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlembicVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alembicVersionDo) Debug() IAlembicVersionDo {
	return a.withDO(a.DO.Debug())
}

func (a alembicVersionDo) WithContext(ctx context.Context) IAlembicVersionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alembicVersionDo) ReadDB() IAlembicVersionDo {
	return a.Clauses(dbresolver.Read)
}

func (a alembicVersionDo) WriteDB() IAlembicVersionDo {
	return a.Clauses(dbresolver.Write)
}

func (a alembicVersionDo) Session(config *gorm.Session) IAlembicVersionDo {
	return a.withDO(a.DO.Session(config))
}

func (a alembicVersionDo) Clauses(conds ...clause.Expression) IAlembicVersionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alembicVersionDo) Returning(value interface{}, columns ...string) IAlembicVersionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alembicVersionDo) Not(conds ...gen.Condition) IAlembicVersionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alembicVersionDo) Or(conds ...gen.Condition) IAlembicVersionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alembicVersionDo) Select(conds ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alembicVersionDo) Where(conds ...gen.Condition) IAlembicVersionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alembicVersionDo) Order(conds ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alembicVersionDo) Distinct(cols ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alembicVersionDo) Omit(cols ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alembicVersionDo) Join(table schema.Tabler, on ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alembicVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alembicVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alembicVersionDo) Group(cols ...field.Expr) IAlembicVersionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alembicVersionDo) Having(conds ...gen.Condition) IAlembicVersionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alembicVersionDo) Limit(limit int) IAlembicVersionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alembicVersionDo) Offset(offset int) IAlembicVersionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alembicVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlembicVersionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alembicVersionDo) Unscoped() IAlembicVersionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alembicVersionDo) Create(values ...*model.AlembicVersion) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alembicVersionDo) CreateInBatches(values []*model.AlembicVersion, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alembicVersionDo) Save(values ...*model.AlembicVersion) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alembicVersionDo) First() (*model.AlembicVersion, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlembicVersion), nil
	}
}

func (a alembicVersionDo) Take() (*model.AlembicVersion, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlembicVersion), nil
	}
}

func (a alembicVersionDo) Last() (*model.AlembicVersion, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlembicVersion), nil
	}
}

func (a alembicVersionDo) Find() ([]*model.AlembicVersion, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlembicVersion), err
}

func (a alembicVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlembicVersion, err error) {
	buf := make([]*model.AlembicVersion, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alembicVersionDo) FindInBatches(result *[]*model.AlembicVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alembicVersionDo) Attrs(attrs ...field.AssignExpr) IAlembicVersionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alembicVersionDo) Assign(attrs ...field.AssignExpr) IAlembicVersionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alembicVersionDo) Joins(fields ...field.RelationField) IAlembicVersionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alembicVersionDo) Preload(fields ...field.RelationField) IAlembicVersionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alembicVersionDo) FirstOrInit() (*model.AlembicVersion, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlembicVersion), nil
	}
}

func (a alembicVersionDo) FirstOrCreate() (*model.AlembicVersion, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlembicVersion), nil
	}
}

func (a alembicVersionDo) FindByPage(offset int, limit int) (result []*model.AlembicVersion, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alembicVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alembicVersionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alembicVersionDo) Delete(models ...*model.AlembicVersion) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alembicVersionDo) withDO(do gen.Dao) *alembicVersionDo {
	a.DO = *do.(*gen.DO)
	return a
}
