// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ai-learn-english/internal/database/model"
)

func newChunk(db *gorm.DB, opts ...gen.DOOption) chunk {
	_chunk := chunk{}

	_chunk.chunkDo.UseDB(db, opts...)
	_chunk.chunkDo.UseModel(&model.Chunk{})

	tableName := _chunk.chunkDo.TableName()
	_chunk.ALL = field.NewAsterisk(tableName)
	_chunk.ID = field.NewInt64(tableName, "id")
	_chunk.DocumentID = field.NewInt64(tableName, "document_id")
	_chunk.ChunkIndex = field.NewInt32(tableName, "chunk_index")
	_chunk.PageIndex = field.NewInt32(tableName, "page_index")
	_chunk.Content = field.NewString(tableName, "content")
	_chunk.ContentPreview = field.NewString(tableName, "content_preview")
	_chunk.TokenCount = field.NewInt32(tableName, "token_count")
	_chunk.MilvusCollection = field.NewString(tableName, "milvus_collection")
	_chunk.MilvusID = field.NewInt64(tableName, "milvus_id")
	_chunk.ContentHash = field.NewString(tableName, "content_hash")
	_chunk.CreatedAt = field.NewTime(tableName, "created_at")

	_chunk.fillFieldMap()

	return _chunk
}

type chunk struct {
	chunkDo chunkDo

	ALL              field.Asterisk
	ID               field.Int64
	DocumentID       field.Int64
	ChunkIndex       field.Int32
	PageIndex        field.Int32
	Content          field.String
	ContentPreview   field.String
	TokenCount       field.Int32
	MilvusCollection field.String
	MilvusID         field.Int64
	ContentHash      field.String
	CreatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (c chunk) Table(newTableName string) *chunk {
	c.chunkDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chunk) As(alias string) *chunk {
	c.chunkDo.DO = *(c.chunkDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chunk) updateTableName(table string) *chunk {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.DocumentID = field.NewInt64(table, "document_id")
	c.ChunkIndex = field.NewInt32(table, "chunk_index")
	c.PageIndex = field.NewInt32(table, "page_index")
	c.Content = field.NewString(table, "content")
	c.ContentPreview = field.NewString(table, "content_preview")
	c.TokenCount = field.NewInt32(table, "token_count")
	c.MilvusCollection = field.NewString(table, "milvus_collection")
	c.MilvusID = field.NewInt64(table, "milvus_id")
	c.ContentHash = field.NewString(table, "content_hash")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *chunk) WithContext(ctx context.Context) IChunkDo { return c.chunkDo.WithContext(ctx) }

func (c chunk) TableName() string { return c.chunkDo.TableName() }

func (c chunk) Alias() string { return c.chunkDo.Alias() }

func (c chunk) Columns(cols ...field.Expr) gen.Columns { return c.chunkDo.Columns(cols...) }

func (c *chunk) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chunk) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["document_id"] = c.DocumentID
	c.fieldMap["chunk_index"] = c.ChunkIndex
	c.fieldMap["page_index"] = c.PageIndex
	c.fieldMap["content"] = c.Content
	c.fieldMap["content_preview"] = c.ContentPreview
	c.fieldMap["token_count"] = c.TokenCount
	c.fieldMap["milvus_collection"] = c.MilvusCollection
	c.fieldMap["milvus_id"] = c.MilvusID
	c.fieldMap["content_hash"] = c.ContentHash
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c chunk) clone(db *gorm.DB) chunk {
	c.chunkDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chunk) replaceDB(db *gorm.DB) chunk {
	c.chunkDo.ReplaceDB(db)
	return c
}

type chunkDo struct{ gen.DO }

type IChunkDo interface {
	gen.SubQuery
	Debug() IChunkDo
	WithContext(ctx context.Context) IChunkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChunkDo
	WriteDB() IChunkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChunkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChunkDo
	Not(conds ...gen.Condition) IChunkDo
	Or(conds ...gen.Condition) IChunkDo
	Select(conds ...field.Expr) IChunkDo
	Where(conds ...gen.Condition) IChunkDo
	Order(conds ...field.Expr) IChunkDo
	Distinct(cols ...field.Expr) IChunkDo
	Omit(cols ...field.Expr) IChunkDo
	Join(table schema.Tabler, on ...field.Expr) IChunkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChunkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChunkDo
	Group(cols ...field.Expr) IChunkDo
	Having(conds ...gen.Condition) IChunkDo
	Limit(limit int) IChunkDo
	Offset(offset int) IChunkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChunkDo
	Unscoped() IChunkDo
	Create(values ...*model.Chunk) error
	CreateInBatches(values []*model.Chunk, batchSize int) error
	Save(values ...*model.Chunk) error
	First() (*model.Chunk, error)
	Take() (*model.Chunk, error)
	Last() (*model.Chunk, error)
	Find() ([]*model.Chunk, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Chunk, err error)
	FindInBatches(result *[]*model.Chunk, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Chunk) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChunkDo
	Assign(attrs ...field.AssignExpr) IChunkDo
	Joins(fields ...field.RelationField) IChunkDo
	Preload(fields ...field.RelationField) IChunkDo
	FirstOrInit() (*model.Chunk, error)
	FirstOrCreate() (*model.Chunk, error)
	FindByPage(offset int, limit int) (result []*model.Chunk, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChunkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chunkDo) Debug() IChunkDo {
	return c.withDO(c.DO.Debug())
}

func (c chunkDo) WithContext(ctx context.Context) IChunkDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chunkDo) ReadDB() IChunkDo {
	return c.Clauses(dbresolver.Read)
}

func (c chunkDo) WriteDB() IChunkDo {
	return c.Clauses(dbresolver.Write)
}

func (c chunkDo) Session(config *gorm.Session) IChunkDo {
	return c.withDO(c.DO.Session(config))
}

func (c chunkDo) Clauses(conds ...clause.Expression) IChunkDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chunkDo) Returning(value interface{}, columns ...string) IChunkDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chunkDo) Not(conds ...gen.Condition) IChunkDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chunkDo) Or(conds ...gen.Condition) IChunkDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chunkDo) Select(conds ...field.Expr) IChunkDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chunkDo) Where(conds ...gen.Condition) IChunkDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chunkDo) Order(conds ...field.Expr) IChunkDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chunkDo) Distinct(cols ...field.Expr) IChunkDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chunkDo) Omit(cols ...field.Expr) IChunkDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chunkDo) Join(table schema.Tabler, on ...field.Expr) IChunkDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chunkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChunkDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chunkDo) RightJoin(table schema.Tabler, on ...field.Expr) IChunkDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chunkDo) Group(cols ...field.Expr) IChunkDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chunkDo) Having(conds ...gen.Condition) IChunkDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chunkDo) Limit(limit int) IChunkDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chunkDo) Offset(offset int) IChunkDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chunkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChunkDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chunkDo) Unscoped() IChunkDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chunkDo) Create(values ...*model.Chunk) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chunkDo) CreateInBatches(values []*model.Chunk, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chunkDo) Save(values ...*model.Chunk) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chunkDo) First() (*model.Chunk, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chunk), nil
	}
}

func (c chunkDo) Take() (*model.Chunk, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chunk), nil
	}
}

func (c chunkDo) Last() (*model.Chunk, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chunk), nil
	}
}

func (c chunkDo) Find() ([]*model.Chunk, error) {
	result, err := c.DO.Find()
	return result.([]*model.Chunk), err
}

func (c chunkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Chunk, err error) {
	buf := make([]*model.Chunk, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chunkDo) FindInBatches(result *[]*model.Chunk, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chunkDo) Attrs(attrs ...field.AssignExpr) IChunkDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chunkDo) Assign(attrs ...field.AssignExpr) IChunkDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chunkDo) Joins(fields ...field.RelationField) IChunkDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chunkDo) Preload(fields ...field.RelationField) IChunkDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chunkDo) FirstOrInit() (*model.Chunk, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chunk), nil
	}
}

func (c chunkDo) FirstOrCreate() (*model.Chunk, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Chunk), nil
	}
}

func (c chunkDo) FindByPage(offset int, limit int) (result []*model.Chunk, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chunkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chunkDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chunkDo) Delete(models ...*model.Chunk) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chunkDo) withDO(do gen.Dao) *chunkDo {
	c.DO = *do.(*gen.DO)
	return c
}
