// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	AlembicVersion *alembicVersion
	Chunk          *chunk
	Document       *document
	Message        *message
	User           *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AlembicVersion = &Q.AlembicVersion
	Chunk = &Q.Chunk
	Document = &Q.Document
	Message = &Q.Message
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		AlembicVersion: newAlembicVersion(db, opts...),
		Chunk:          newChunk(db, opts...),
		Document:       newDocument(db, opts...),
		Message:        newMessage(db, opts...),
		User:           newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AlembicVersion alembicVersion
	Chunk          chunk
	Document       document
	Message        message
	User           user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		AlembicVersion: q.AlembicVersion.clone(db),
		Chunk:          q.Chunk.clone(db),
		Document:       q.Document.clone(db),
		Message:        q.Message.clone(db),
		User:           q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		AlembicVersion: q.AlembicVersion.replaceDB(db),
		Chunk:          q.Chunk.replaceDB(db),
		Document:       q.Document.replaceDB(db),
		Message:        q.Message.replaceDB(db),
		User:           q.User.replaceDB(db),
	}
}

type queryCtx struct {
	AlembicVersion IAlembicVersionDo
	Chunk          IChunkDo
	Document       IDocumentDo
	Message        IMessageDo
	User           IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AlembicVersion: q.AlembicVersion.WithContext(ctx),
		Chunk:          q.Chunk.WithContext(ctx),
		Document:       q.Document.WithContext(ctx),
		Message:        q.Message.WithContext(ctx),
		User:           q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
