// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChunk = "chunks"

// Chunk mapped from table <chunks>
type Chunk struct {
	ID               int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DocumentID       int64      `gorm:"column:document_id;not null" json:"document_id"`
	ChunkIndex       int32      `gorm:"column:chunk_index;not null" json:"chunk_index"`
	PageIndex        *int32     `gorm:"column:page_index" json:"page_index"`
	Content          string     `gorm:"column:content;not null" json:"content"`
	ContentPreview   *string    `gorm:"column:content_preview" json:"content_preview"`
	TokenCount       *int32     `gorm:"column:token_count" json:"token_count"`
	MilvusCollection string     `gorm:"column:milvus_collection;not null" json:"milvus_collection"`
	MilvusID         int64      `gorm:"column:milvus_id;not null" json:"milvus_id"`
	ContentHash      string     `gorm:"column:content_hash;not null" json:"content_hash"`
	CreatedAt        *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Chunk's table name
func (*Chunk) TableName() string {
	return TableNameChunk
}
