// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDocument = "documents"

// Document mapped from table <documents>
type Document struct {
	ID               int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID           int64      `gorm:"column:user_id;not null" json:"user_id"`
	Title            *string    `gorm:"column:title" json:"title"`
	OriginalFilename *string    `gorm:"column:original_filename" json:"original_filename"`
	FilePath         *string    `gorm:"column:file_path" json:"file_path"`
	Language         *string    `gorm:"column:language;default:en" json:"language"`
	PageCount        *int32     `gorm:"column:page_count" json:"page_count"`
	Sha256           *string    `gorm:"column:sha256" json:"sha256"`
	UploadedAt       *time.Time `gorm:"column:uploaded_at;default:CURRENT_TIMESTAMP" json:"uploaded_at"`
}

// TableName Document's table name
func (*Document) TableName() string {
	return TableNameDocument
}
