// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64      `gorm:"column:user_id;not null" json:"user_id"`
	Role       string     `gorm:"column:role;not null" json:"role"`
	Content    string     `gorm:"column:content;not null" json:"content"`
	DocumentID *int64     `gorm:"column:document_id" json:"document_id"`
	CreatedAt  *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
