// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email        string     `gorm:"column:email;not null" json:"email"`
	Username     *string    `gorm:"column:username" json:"username"`
	PasswordHash *string    `gorm:"column:password_hash" json:"password_hash"`
	CreatedAt    *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
