"""change role type

Revision ID: 5a3e1ff85564
Revises: 7f3a2b7f3a8b
Create Date: 2025-11-10 16:46:45.022420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a3e1ff85564'
down_revision = '7f3a2b7f3a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'content',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('chunks', 'milvus_collection',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               nullable=False)
    op.alter_column('chunks', 'content_hash',
               existing_type=mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=64),
               type_=sa.String(length=64),
               nullable=False)
    op.drop_column('documents', 'status')
    op.alter_column('messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('user', 'assistant', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.add_column('documents', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), server_default=sa.text("'uploaded'"), nullable=False))
    op.alter_column('chunks', 'content_hash',
               existing_type=sa.String(length=64),
               type_=mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=64),
               nullable=True)
    op.alter_column('chunks', 'milvus_collection',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               nullable=True)
    op.alter_column('chunks', 'content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True)
    # ### end Alembic commands ###

